### PR TITLE
update dev dependencies and follow types

### PR DESCRIPTION
**Pull request by dai-shi**
No longer uses `FC`.

### CODE REVIEW

**Comment by hcharley** [comment]
I think I am in need of this PR, as the type definition of `FC` no longer includes `children` in it.

**Comment by dai-shi** [comment]
Okay, let's release this.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/1.3.10

**Comment by hcharley** [comment]
Oh! Thank you so much for your responsiveness @dai-shi !! I am downloading now.

This is a big help as I was just about to go through my codebase and put `Provider as any` everywhere

**Pull request merged**
