### PR TITLE
fix: handle missing runWithPriority with preact

### LINKED ISSUE #35: Preact: scheduler
I'm trying to use jotai with Preact with 
```
  "alias": {
    "react": "preact/compat",
    "react-dom": "preact/compat",
    "scheduler": false
  }
```
but this of course fails with `t.unstable_runWithPriority is not a function` because `scheduler` is needed...

Is there a way to make it work?

### PR DESCRIPTION
**Pull request by dai-shi**
close #35

### CODE REVIEW

**Comment by dai-shi** [comment]
@mischnic 
Assuming you are familiar with yarn resolutions, would you be able to try the build by codesandbox in this PR?

**Comment by mischnic** [comment]
Setting a new state doesn't seem to work: https://github.com/mischnic/jotai-preact-demo
The text in the input field cannot be changed.

**Comment by dai-shi** [comment]
Hmm, we need to investigate more to understand the problem.
Would you help? Could you try use-context-selector only example to see if the issue is this or jotai?

**Comment by mischnic** [comment]
I've updated the repo above with the counter example from the readme:

https://user-images.githubusercontent.com/4586894/103548812-a41f8980-4ea6-11eb-8d96-70663b46d41a.mov

With Preact, the counters aren't incrementing and after the first update, the other component is also rerendering.

(Compared to React: https://codesandbox.io/s/react-use-context-selector-xm235)

**Comment by mischnic** [comment]
The actual state in the state provider is updating correctly and the component is rerendering, but `useContextSelector(context, (v) => v[0].count1)` always returns 0.

Bildschirmfoto 2021-01-04 um 16 13 46

**Comment by mischnic** [comment]
This line executes

https://github.com/dai-shi/use-context-selector/blob/47795a18b3521458c0af01a1389a3bd18ed9a0b4/src/index.ts#L152

and `useContextSelector` is called again. After that, the reducer is called again with React. But with Preact, nothing happens:

Bildschirmfoto 2021-01-04 um 16 53 08

React:

Bildschirmfoto 2021-01-04 um 16 53 37

**Comment by dai-shi** [comment]
Nice! Thanks for your investigation.

I was also reading the useReducer code in preact.
https://github.com/preactjs/preact/blob/d29d8580245eba65135f943f24f945cf95f01a1e/hooks/src/index.js#L136-L157
It will replace the reducer function in render, but not re-evaluate it. So, the preact behavior is different from react.

I can't come up with any solutions other than feature detection. It's regrettable, but let's see if it works.

**Comment by dai-shi** [comment]
https://github.com/mischnic/jotai-preact-demo

Your example seems to work fine with the new build.

```diff
diff --git a/package.json b/package.json
index abd0199..2f77f16 100644
--- a/package.json
+++ b/package.json
@@ -4,7 +4,7 @@
                "preact": "^10.5.9"
        },
        "resolutions": {
-               "use-context-selector": "file:./use-context-selector.tgz"
+               "use-context-selector": "https://pkg.csb.dev/dai-shi/use-context-selector/commit/29b09817/use-context-selector"
        },
        "scripts": {
                "start": "parcel index.html"
```

**Comment by mischnic** [comment]
Great! The state seems to update now, but there are still unnecessary rerenders:

https://user-images.githubusercontent.com/4586894/103634583-8e15d580-4f47-11eb-9e29-38b9f5fec71d.mov

Do you have a small example where Preact's useReducer behaves differently from React? Maybe they could fix that in Preact if we open an issue for this.

**Comment by dai-shi** [comment]
https://overreacted.io/a-complete-guide-to-useeffect/#why-usereducer-is-the-cheat-mode-of-hooks
This article might help. I'm not sure if Preact should follow the React behavior.

**Comment by mischnic** [comment]
That example works fine: https://codesandbox.io/s/preact-usereducer-cheat-hkhgv 

At least for `preact/compat`, they usually strive for 100% compatibility.

**Comment by dai-shi** [comment]
Hmmm, I tried to reproduce the behavior in the codesandbox, without success. (Maybe the double reducer invocation behavior is specific to the combination with `useContext`??

**Comment by dai-shi** [comment]
@mischnic Thanks for the repro!

Meanwhile, I came up with another solution. This looks reasonable in code. Would you try if it works with preact?

**Comment by mischnic** [comment]
Yes. Both use-context-selector itself and jotai work correctly now

**Comment by dai-shi** [comment]
Thanks. Let's merge and release this then.

Thanks again for raising this up and investigating in detail.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/1.3.5

**Comment by mischnic** [comment]
Thanks!

**Pull request merged**
