### PR TITLE
[v2] new API and new implementation with useMutableSource

### PR DESCRIPTION
**Pull request by dai-shi**
- new API: `useContext(context, selector)`
- new implementation with `useMutableSource` in [the RFC](https://github.com/reactjs/rfcs/pull/147)
- in TypeScript

Check list:
- [x] implementation
- [x] readme

### CODE REVIEW

**Comment by dai-shi** [comment]
Just did a quick benchmark. This is very simplified usage, and it may not reflect real use cases. `react-redux-use-context-selector-2-keyed` represents ff52b56 with `useMutableSource`-enabled (wip) React. (while others use React 16.8.6, so they are totally incomparable.)

image

**Comment by dai-shi** [comment]
Here's another trial. both v1 and v2 use https://github.com/facebook/react/commit/b028a0bf6b3bc96038376a8437029c0377abef13.

image

**Comment by dai-shi** [comment]
If we still need to use `calculateChangedBits`, we should stick with v1 without useMutableSource. That's very unfortunate though.

**Comment by dai-shi** [comment]
### The current status

I'm giving up on passing `02_tearing_spec` in v2, because I don't want to use the undocumented `calculateChangedBits` in v2. Unfortunately, useMutableSource will not be able to solve this spec (which is not in their goal). I'd leave it as a limitation.

**Comment by dai-shi** [comment]
Hm? If we mutate ref in effect, startTransiton doesn't work. It's a huge drawback.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.1

**Comment by dai-shi** [comment]
https://github.com/facebook/react/pull/18296#issue-387534291 This might be related to the reason `__tests__/03_stale_props_spec.tsx` is failing now. Not sure.

**Comment by yisar** [comment]
Does the new implementation no longer need context? This is great.

**Comment by dai-shi** [comment]
@yisar Does this answer your question: v2 implementation doesn't rely on context propagation, but use useMutableSource for updating components "selectively".

**Comment by yisar** [comment]
@dai-shi Great job. 
I've always wanted to choose one of implementations in the [speculative mode](https://github.com/reactjs/rfcs/pull/150) and use mutable source, but I've been uncertain about it. Thank you for your implementation, which may be an inspiration.

**Comment by dai-shi** [comment]
@yisar If the Speculative mode was really implemented into React core, it would be better. But, it will take time.
Until then, this library provides a userland alternative. It provides the same API with some limitations.
I'm not sure about your requirement, but if you are happy with low-level APIs, it would be good to use `useMutableSource` directly. If you want a handy library ready to use, this library would be one of them. Also, another library of mine could be a candidate: [React Tracked](https://react-tracked.js.org) and its [PR](https://github.com/dai-shi/react-tracked/pull/43) with useMutableSource.

**Comment by yisar** [comment]
Yep, I wrote a react like framework called [fre](https://github.com/yisar/fre). Now I want to implement context API. I have two options:

1. Try to implement build-in Speculative mode.

2. Try to implement usemutablesource and guide users to use 'use-context-selector'`

Because the context API was not implemented before, V1 is not available, but V2 seems to be an inspiration. But I still need advice.

**Comment by dai-shi** [comment]
Ah, okay. You are working on your own implementation. Then, the two options make sense.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.2

**Comment by dai-shi** [comment]
Published again: https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.3

**Comment by victorporof** [comment]
How can I try this out? I've upgraded to "react": "experimental" and "react-dom": "experimental", and using "use-context-selector": "^2.0.0-alpha.3". However I'm getting a 
```
Uncaught TypeError: dispatcher.useMutableSource is not a function
    at Object.useMutableSource (react.development.js:1744)
```
when running.

**Comment by dai-shi** [comment]
That looks correct. I will try again later on my end.

**Comment by victorporof** [comment]
@dai-shi thank you!

**Comment by dai-shi** [comment]
@victorporof 

Here's the codesandbox example: https://codesandbox.io/s/nostalgic-cloud-ujh1e

I don't see your error.

There's one note about `useMutableSource`. `getSnapshot` can't return a function now. It should be fixed in React. So, for now, I use a workaround: `useMemo(() => ({ dispatch }), [])`

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.4

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.5

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.6

**Comment by dai-shi** [comment]
https://www.npmjs.com/package/use-context-selector/v/2.0.0-alpha.9

**Comment by dai-shi** [comment]
uMS will not land, and v1.3 already works well with concurrent rendering at its best. Closing.

**Comment by HansBrende** [comment]
@dai-shi the replacement for `useMutableSource` is `useSyncExternalStore`.... why not use that function instead?

**Comment by dai-shi** [comment]
It does work as we want. It's "Sync" and its behavior isn't well in concurrent rendering.

**Pull request closed without merging**
